# ------------------------------------
# complete
# ------------------------------------

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"

[[plugins]]
repo = 'Shougo/neocomplcache.vim'
if = "! has('lua')"

[[plugins]]
repo = 'Shougo/neocomplcache-clang'
if = "! has('lua')"

# ------------------------------------
# lang
# ------------------------------------

# if has('python') || has('python3')
#   NeoBundleLazy 'ternjs/tern_for_vim'
#   if neobundle#tap('tern_for_vim')
#     call neobundle#config({
#     \   'build': {
#     \     'others': 'npm install'
#     \   },
#     \   'autoload': {
#     \     'functions': ['tern#Complete', 'tern#Enable'],
#     \     'filetypes': ['javascript']
#     \   },
#     \   'commands': [
#     \     'TernDef', 'TernDoc', 'TernType', 'TernRefs', 'TernRename'
#     \   ]
#     \ })
#
#     let g:tern_map_keys = 0
#
#     call neobundle#untap()
#   endif
# endif

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['perl']

[[plugins]]
repo = 'c9s/perlomni.vim'
on_ft = ['perl']

# [[plugins]]
# repo = 'Shougo/vim-nyaos'
# on_ft = 'nyaos'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'jade']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss', 'sass']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'vim-scripts/css_color'

[[plugins]]
repo = 'vim-scripts/tex-syntax'
on_ft = ['tex']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

# [[plugins]]
# repo = 'klen/python-mode'
# on_ft = ['python']

# JavaScript
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js', 'javascript']

# typescript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['ts', 'typescript']

[[plugins]]
repo = 'ryym/vim-riot'
on_ft = ['riot']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
